name: RCZ cron

on:
  schedule:
    - cron:  '0,15,30,45 * * * *'

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: curl -f https://daffodil-lucky-note.glitch.me/poll
